## clients_users
services:
    App\Clients\Application\Listener\User\LoggedInSubscriber:
        autowire: false
    app.clients.application.listener.user.logged_in_subscriber:
        class: App\Clients\Application\Listener\User\LoggedInSubscriber
        arguments: ['@app.clients.infrastructure.user.repository', '@doctrine.orm.entity_manager']
        tags:
            - { name: kernel.event_subscriber }

    app.clients.infrastructure.user.repository:
        public: true
        class: 'App\Clients\Infrastructure\User\Repository\UserRepository'
        factory: '@App\Clients\Infrastructure\User\Repository\UserRepositoryFactory'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@infrastructure.criteria.criteria_factory'
    app.clients.infrastructure.user.paginator:
        public: true
        class: 'Infrastructure\Paginator\PagerfantaPaginator'
        factory: '@crud.factory.paginator_factory'
        arguments:
            - '@infrastructure.criteria.criteria_factory'
            - 'App\Clients\Domain\User\User'

    app.clients.application.validator.constraints.user_exist_validator:
        class: App\Clients\Application\Validator\Constraints\UserExistValidator
        arguments: ['@app.clients.infrastructure.user.repository']
        tags:
            - { name: validator.constraint_validator }
    app.clients.application.validator.constraints.user_not_exist_validator:
        class: App\Clients\Application\Validator\Constraints\UserNotExistValidator
        arguments: ['@app.clients.infrastructure.user.repository']
        tags:
            - { name: validator.constraint_validator }
    app.clients.application.validator.constraints.client_exist_validator:
        class: App\Clients\Application\Validator\Constraints\ClientExistValidator
        arguments: ['@app.clients.infrastructure.client.repository']
        tags:
            - { name: validator.constraint_validator }
    App\Clients\Application\Validator\Constraints\ClientExistValidator: '@app.clients.application.validator.constraints.client_exist_validator'

    ## UseCase
    app.clients.domain.user.use_case.register.handler:
        public: true
        class: App\Clients\Domain\User\UseCase\Register\Handler
        arguments:
            - '@app.clients.infrastructure.user.repository'
            - '@app.clients.infrastructure.company.repository'
            - '@App\Clients\Infrastructure\User\Service\PasswordEncoder'
            - '@doctrine.orm.entity_manager'
    app.clients.domain.user.use_case.create.handler:
        public: true
        class: App\Clients\Domain\User\UseCase\Create\Handler
        arguments:
            - '@app.clients.infrastructure.user.repository'
            - '@App\Clients\Infrastructure\User\Service\PasswordEncoder'
            - '@doctrine.orm.entity_manager'
    app.clients.domain.user.use_case.update.handler:
        public: true
        class: App\Clients\Domain\User\UseCase\Update\Handler
        arguments:
            - '@app.clients.infrastructure.user.repository'
            - '@App\Clients\Infrastructure\User\Service\PasswordEncoder'
            - '@doctrine.orm.entity_manager'
    app.clients.domain.user.use_case.delete.handler:
        public: true
        class: App\Clients\Domain\User\UseCase\Delete\Handler
        arguments:
            - '@app.clients.infrastructure.user.repository'
            - '@doctrine.orm.entity_manager'
    app.clients.domain.user.use_case.change_status.handler:
        public: true
        class: App\Clients\Domain\User\UseCase\ChangeStatus\Handler
        arguments:
            - '@app.clients.infrastructure.user.repository'
            - '@doctrine.orm.entity_manager'
    app.clients.domain.user.use_case.forgot_pass.handler:
        public: true
        class: App\Clients\Domain\User\UseCase\ForgotPass\Handler
        arguments:
            - '@app.clients.infrastructure.user.repository'
            - '@doctrine.orm.entity_manager'
            - '@App\Clients\Infrastructure\User\Service\TokenGenerator'
            - '@MailerBundle\Service\Sender'

    ## end UseCase

    app.clients.action.backend.user.list_action.query_request:
        public: true
        class: App\Clients\Action\Backend\User\ListAction\QueryRequest
        arguments:
            - '@request_stack'
            - '@security.token_storage'
            - '@security.authorization_checker'

    app.clients.view.user.form.data_mapper.form_data_mapper:
        public: true
        class: App\Clients\View\User\Form\DataMapper\FormDataMapper

    app.clients.application.validator.constraints.manager_exist_validator:
        class: App\Clients\Application\Validator\Constraints\ManagerExistValidator
        arguments: ['@service_container']
        tags:
            - { name: validator.constraint_validator }

    app.api.action.api.v1.users.create_handler_request:
        public: true
        class: App\Clients\Domain\User\UseCase\Create\HandlerRequest
        factory: '@App\Api\Action\Api\V1\Users\CreateHandlerRequestFactory'
        arguments: ['@request_stack', '@myself']

    App\Api\Action\Api\V1\Users\UpdateHandlerRequestFactory:
        autowire: false
    app.api.action.api.v1.users.update_handler_request_factory:
        class: App\Api\Action\Api\V1\Users\UpdateHandlerRequestFactory
        arguments:
            - '@request_stack'
            - '@myself'
            - '@app.clients.infrastructure.user.repository'

    app.api.action.api.v1.users.update_handler_request:
        public: true
        class: App\Clients\Domain\User\UseCase\Update\HandlerRequest
        factory: '@app.api.action.api.v1.users.update_handler_request_factory'

    App\Api\Action\Api\V1\Users\DeleteHandlerRequestFactory:
        autowire: false
    app.api.action.api.v1.users.delete_handler_request_factory:
        class: App\Api\Action\Api\V1\Users\DeleteHandlerRequestFactory
        arguments:
            - '@request_stack'
            - '@myself'
            - '@app.clients.infrastructure.user.repository'
    app.api.action.api.v1.users.delete_handler_request:
        public: true
        class: App\Clients\Domain\User\UseCase\Delete\HandlerRequest
        factory: '@app.api.action.api.v1.users.delete_handler_request_factory'

    App\Api\Action\Api\V1\Users\ChangeStatusHandlerRequestFactory:
        autowire: false
    app.api.action.api.v1.users.change_status_handler_request_factory:
        class: App\Api\Action\Api\V1\Users\ChangeStatusHandlerRequestFactory
        arguments:
            - '@request_stack'
            - '@myself'
            - '@app.clients.infrastructure.user.repository'
    app.api.action.api.v1.users.change_status_handler_request:
        public: true
        class: App\Clients\Domain\User\UseCase\ChangeStatus\HandlerRequest
        factory: '@app.api.action.api.v1.users.change_status_handler_request_factory'

    ## api update profile
    App\Api\Action\Api\V1\Me\UpdateAction\HandlerRequestFactory:
        autowire: false
    app.api.action.api.v1.me.update_action.handler_request_factory:
        class: App\Api\Action\Api\V1\Me\UpdateAction\HandlerRequestFactory
        arguments:
            - '@request_stack'
            - '@myself'
    app.api.action.api.v1.me.update_action.handler_request:
        public: true
        class: App\Clients\Domain\User\UseCase\UpdateProfile\HandlerRequest
        factory: '@app.api.action.api.v1.me.update_action.handler_request_factory'

    app.clients.domain.user.use_case.update_profile.handler:
        public: true
        class: App\Clients\Domain\User\UseCase\UpdateProfile\Handler
        arguments:
            - '@app.clients.infrastructure.user.repository'
            - '@App\Clients\Infrastructure\User\Service\PasswordEncoder'
            - '@doctrine.orm.entity_manager'

    ## api controllers
    App\Api\Action\Api\V1\Users\ListAction\QueryRequest:
        autowire: false
    app.api.action.api.v1.users.list_action.query_request:
        public: true
        class: App\Api\Action\Api\V1\Users\ListAction\QueryRequest
        factory: '@App\Api\Action\Api\V1\Users\ListAction\QueryRequestFactory'
        arguments: ['@request_stack', '@myself']

    App\Api\Action\Api\V1\Users\ReadAction\QueryRequest:
        autowire: false
    app.api.action.api.v1.users.read_action.query_request:
        public: true
        class: App\Api\Action\Api\V1\Users\ReadAction\QueryRequest
        factory: '@App\Api\Action\Api\V1\Users\ReadAction\QueryRequestFactory'
        arguments: ['@request_stack', '@myself']

    App\Api\Action\Api\V1\Users\ListAction\PaginatorListService:
        public: true
        class: App\Api\Action\Api\V1\Users\ListAction\PaginatorListService
        arguments:
            - '@app.clients.infrastructure.user.paginator'
            - '@app.clients.infrastructure.user.repository'
            - '@myself'

    app.api.action.api.v1.users.read_action.read_service:
        public: true
        class: App\Api\Crud\Service\ReadService
        arguments: ['@app.clients.infrastructure.user.repository']

    app.api.resource.update_profile.data_transformer:
        public: true
        class: App\Api\Crud\DataTransformer\ObjectDataTransformer
        arguments:
            - '@serializer'
            - '@App\Api\Resource\ProfileUpdate'
    ## end api controllers

    app.api.resource.company_user.data_transformer:
        public: true
        class: App\Api\Crud\DataTransformer\ObjectDataTransformer
        arguments:
            - '@serializer'
            - '@App\Api\Resource\CompanyUser'
    ## controller actions
    App\Api\Action\Api\V1\Me\ProfileAction\ProfileAction:
        class: App\Api\Action\Api\V1\Me\ProfileAction\ProfileAction
        arguments:
            - '@myself'
            - '@app.users.infrastructure.user.repository'
            - '@App\Api\Resource\MeProfile'
            - '@app.api.crud.json_response'
        tags: ['controller.service_arguments']

    App\Clients\Action\Frontend\User\PassRecoverAction:
        class: App\Clients\Action\Frontend\User\PassRecoverAction
        arguments:
            - '@app.clients.infrastructure.user.repository'
            - '@twig'
            - '@form.factory'
            - '@app.clients.domain.user.use_case.recover_pass.handler'
            - '@serializer'
            - '@router.default'
        tags:
            - { name: controller.service_arguments }
    app.clients.domain.user.use_case.recover_pass.handler:
        class: App\Clients\Domain\User\UseCase\RecoverPass\Handler
        arguments:
            - '@app.clients.infrastructure.user.repository'
            - '@App\Clients\Infrastructure\User\Service\PasswordEncoder'
            - '@doctrine.orm.default_entity_manager'

    app.api.action.api.v1.password_recovery.handler_request:
        public: true
        factory: '@App\Api\Action\Api\V1\PasswordRecovery\HandlerRequestFactory'
        class: App\Clients\Domain\User\UseCase\ForgotPass\HandlerRequest
        arguments: ['@request_stack', '@serializer.normalizer.object']

    App\Clients\Action\Backend\User\ChangeStatus\ChangeStatusHandlerRequestFactory:
        arguments:
            - '@request_stack'
            - '@security.authorization_checker'
            - '@serializer'
    app.clients.action.backend.user.change_status.handler_request:
        public: true
        class: 'App\Clients\Domain\User\UseCase\ChangeStatus\HandlerRequest'
        factory: '@App\Clients\Action\Backend\User\ChangeStatus\ChangeStatusHandlerRequestFactory'