doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
        driver: 'pdo_pgsql'
        server_version: '10'
        default_table_options:
            charset: utf8
            collate: utf8_unicode_ci
        schema_filter: '~^(?!view_)~'

        types:
            uuid: Ramsey\Uuid\Doctrine\UuidType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        dql:
            string_functions:
                CONTAINS: Opsway\Doctrine\ORM\Query\AST\Functions\Contains
            datetime_functions:
                to_char: App\Doctrine\DQL\ToCharFunction
                date_trunc: App\Doctrine\DQL\DateTruncFunction
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src'
                prefix: 'App'
                alias: App
            Storage\File:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/bundles/files-uploader/src/Domain/Storage'
                prefix: 'FilesUploader\Domain\Storage'
                alias: File