export type TIconType =
	| "chevron-down"       | "chevron-up"  | "chevron-left" | "chevron-right"
	| "check-square"       | "list-square" | "add-square"   | "checkbox-unchecked" | "checkbox-checked"
	| "triangle-down"      | "triangle-up"
	| "burger"   | "menu"  | "close"
	| "feedback" | "comment"
	| "heart"    | "favorite"
	| "export"   | "upload"
	| "trash"    | "delete"
	| "more"     | "dots"
	| "news"     | "cols"
	| "transaction"
	| "calendar"
	| "outside"
	| "reorder"
	| "profile" | "logout"
	| "ticket"
	| "filter"
	| "email"
	| "limit"
	| "phone"
	| "edit"
	| "info"
	| "card"
	| "lock"
	| "cog"
	| "doc"
	| "pending"
	| "home"
	| "bug"
	| string
